### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by nullt3r** [rusty-sediment/sediment#1]
Hello!

Thanks for creating this project; it's rare to find a password filter with a focus on security. I have a couple of questions about the installation process:

- Which registry keys should be configured? Could you give me an example of a Key and its corresponding Value?
- Are there any additional steps I need to follow?
- How to build the lib.rs?

I have gone through the source code and found the registry keys, but I am not sure about the values. I was able to download the database, but it seems to always tell password was compromised, without any error. 

Thanks in advance.

**Comment by ghost** [comment]
Hi!

Thanks for your interest! It's great to see someone checking this out. Admittedly, I've gotten this to a "working" state and haven't found the help to follow through with the most difficult portions now. I still need to learn Wix to create a proper installer, and the code certainly could be cleaned up.

As for this working, there are a few things I was in the middle of recently that would most likely make it break. Optionally normalizing strings is one of those things.

Expected registry keys for this to operate:
- Path (`REG_SZ`): A string that points to the local folder or network share path where the `sled` database resides to save download state.
- DownloadPath (`REG_SZ`): A string that points to the local folder or network share path where the hashes from `haveibeenpwned` are downloaded to and where your custom compromised passwords are stored.
- FilterPath (`REG_SZ`): A string that points to the local folder or network share path where the data structure files themselves are stored. **This should be separate from your download path** and is intended to be the DFS-replicated folder. These files would only be modified when a new download is done and hashes are updated, and even then only a few files and a few blocks within those files should realistically update, heavily reducing the bandwidth necessary to replicate.
- NormalizeFlag (`REG_DWORD`): A 0 or 1 indicating whether to normalize a string (`1`) or leave it alone (`0`).

To build the library would just require installing Rust ([available here](https://www.rust-lang.org/tools/install)) and performing a `cargo build --release`. It should produce a `sediment.dll`. If it doesn't I likely haven't configured the build to do so yet as I hadn't gotten there.

**Comment by nullt3r** [comment]
Thank you. The lib part is not in the build config, but I have added a block to compile cydlib. Was the library working when you compiled it? I have tried it, but it can't be loaded by the Windows.

**Comment by ghost** [comment]
I had not yet reached testing phases for the library itself unfortunately. There are a couple reasons it may be failing such as the logging I'm trying to use (another library for logging directly to Windows event log).

The system event log (source Directory-Services-SAM I believe) should have an error code. If you weren't already aware, part of the install process for password fillers is also listing it in the registry key. Instructions for that can be found [here](https://learn.microsoft.com/en-us/windows/win32/secmgmt/installing-and-registering-a-password-filter-dll).

**Comment by disassembledd** [comment]
Hi @nullt3r, long time no talk! You should be able to use the newly release installer now! It will handle everything for you, and I have tested the DLL itself to ensure it works.
